name: masamune_purchase
description: Plug-in module that provides the billing system function of Masamune framework.
version: 0.8.2
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_purchase

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  masamune: ^0.8.0
  masamune_mobile: ^0.8.0
  http: ^0.13.0
  in_app_purchase: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  # masamune_test: ^0.5.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
