name: masamune_purchase
description: >-
  Plug-in module that provides the billing system function of Masamune framework.
version: 0.5.0+2
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_purchase

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # in app purchase
  http: ^0.12.2
  simple_rsa: ^0.0.5
  in_app_purchase: ^0.3.4
  # Masamune
  masamune_core: ^0.5.0
  masamune_flutter: ^0.5.0
  masamune_localize: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.1.0
  
# dependency_overrides:
#   masamune_core:
#     path: ../masamune_core/
#   masamune_localize:
#     path: ../masamune_localize/
#   masamune_flutter:
#     path: ../masamune_flutter/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
